# tasks file
---
- name: composer.json | create configuration directory
  ansible.builtin.file:
    path: "{{ item.dest | dirname }}"
    state: directory
    mode: 0755
  with_items: "{{ composer_composer_json_map }}"
  become: true
  become_user: "{{ item.owner | default('root') }}"
  tags:
    - composer-composer-json-copy

- name: composer.json | copy files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items: "{{ composer_composer_json_map }}"
  become: true
  become_user: "{{ item.owner | default('root') }}"
  tags:
    - composer-composer-json-copy

- name: composer.json | set github-oauth token
  ansible.builtin.command: >
    {{ composer_install_dir }}/composer config github-oauth.github.com {{ item.github_oauth }}
  args:
    chdir: "{{ item.dest | dirname }}"
  with_items: "{{ composer_composer_json_map }}"
  when: item.github_oauth is defined
  changed_when: false
  become: true
  become_user: "{{ item.owner | default('root') }}"
  tags:
    - composer-composer-json-configure

- name: composer.json | run composer install
  ansible.builtin.command: >
    {{ composer_install_dir }}/composer install --no-ansi --no-progress --no-interaction
    {{ item.options if item.options is defined else '--prefer-dist' }}
  args:
    chdir: "{{ item.dest | dirname }}"
  register: _composer_composer_json_install
  with_items: "{{ composer_composer_json_map }}"
  changed_when: >
    'Nothing to install or update' not in _composer_composer_json_install.stderr
  become: true
  become_user: "{{ item.owner | default('root') }}"
  tags:
    - composer-composer-json-install

- name: composer.json | run composer update
  ansible.builtin.command: >
    {{ composer_install_dir }}/composer update --no-ansi --no-progress --no-interaction
    {{ item.options if item.options is defined else '--prefer-dist' }}
  args:
    chdir: "{{ item.dest | dirname }}"
  register: _composer_composer_json_update
  with_items: "{{ composer_composer_json_map }}"
  when:
    - item.run_update is defined
    - item.run_update
  changed_when: >
    'Nothing to install or update' not in _composer_composer_json_update.stderr
  become: true
  become_user: "{{ item.owner | default('root') }}"
  tags:
    - composer-composer-json-update
