# tasks file
---
- name: install | download  # noqa command-instead-of-module
  ansible.builtin.shell: >
    curl -sSL {{ composer_download_url }} -o {{ composer_install_dir }}/composer
  args:
    creates: "{{ composer_install_dir }}/composer"
  tags:
    - composer-install-download

- name: install | check permissions
  ansible.builtin.file:
    path: "{{ composer_install_dir }}/composer"
    owner: root
    group: root
    mode: '0755'
  tags:
    - composer-install-permissions

- name: install | update to the latest version
  ansible.builtin.command: >
    {{ composer_install_dir }}/composer self-update
  register: _composer_self_update
  changed_when: >
    'Updating to version' in _composer_self_update.stderr or
    'Upgrading to version' in _composer_self_update.stdout
  when: composer_self_update
  tags:
    - composer-install-self-update
