# tasks file
---
- name: install
  ansible.builtin.include_tasks: install.yml
  tags:
    - configuration
    - composer
    - composer-install

- name: composer.json
  ansible.builtin.include_tasks: composer-json.yml
  tags:
    - configuration
    - composer
    - composer-composer-json
